colouring(A,B,C,D,E,F):-
    different(A,B),
    different(A,C),
    different(A,D),
    different(A,F),
    different(B,C),
    different(B,E),
    different(C,D),
    different(C,E),
    different(D,E),
    different(E,F).
    different(red,green).
    different(green,yellow).
    different(red,yellow).
    different(green,red).
    different(yellow,green).
    different(yellow,red).
